matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: SWIFT_VERSION=4.0
    - os: osx
      osx_image: xcode10
      env: SWIFT_VERSION=4.2
    - os: linux
      env: SWIFT_VERSION=4.1
    - os: linux
      env: SWIFT_VERSION=4.2
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift test
